### ISSUE TITLE
v9.0.0 status?

### ISSUE THREAD

**Issue by sklawren** [haihappen/stylelint-config-idiomatic-order#75]
According to npm-check, there is a v9.0.0 available. However, I don't see a tag, release, change log, etc. for version 9.

![Screen Shot 2022-10-03 at 11 22 34](https://user-images.githubusercontent.com/60169661/193490664-adac7d03-d1c2-4f6a-b2da-0b86802c48c5.jpg)

**Comment by sklawren** [comment]
NPM has version 9 as the latest. Have you been hacked?

https://www.npmjs.com/package/stylelint-config-idiomatic-order

**Comment by RodrigoTomeES** [comment]
I think the same, any news on this?

**Comment by sklawren** [comment]
@ream88 Has your npm account been hacked?

**Comment by ghost** [comment]
`index.js` is the same in v.9 and on Github versions, but I've contacted the author via email.

**Comment by ream88** [comment]
Nope, was not hacked, just never had the time to push it to GH as well with the proper tags.

**Comment by ream88** [comment]
Done

**Comment by RodrigoTomeES** [comment]
@ream88 hi, thanks! What are the breaking changes in v9?

**Comment by ream88** [comment]
Updated the dep on `stylelint` to a newer version
