### ISSUE TITLE
Stylelint 15 support

### ISSUE THREAD

**Issue by sklawren** [haihappen/stylelint-config-idiomatic-order#78]
This works with stylelint 15 without issue, but there's a peer dependency warning. Simple to fix by updating to stylelint 15 in your package.json.

```
warning "stylelint-config-idiomatic-order > stylelint-order@5.0.0" has incorrect peer dependency "stylelint@^14.0.0".
```

**Comment by spacedawwwg** [comment]
to get by for now until that PR is merged, I'm using (with yarn):

```JSON
{
  "resolutions": {
    "stylelint-order": "6.0.3"
  }
}
```

**Comment by unikitty37** [comment]
Thanks, @spacedawwwg — npm users should replace `resolutions` with `overrides`, FWIW.
