### ISSUE TITLE
Release v10.0.0 to npm

### ISSUE THREAD

**Issue by Quentame** [haihappen/stylelint-config-idiomatic-order#85]
You seem to have done the work for v10 to exist (as of commit 79d1d6610a0b5d37836b47918d79b17442d17632), but it is not released on [GitHub](https://github.com/ream88/stylelint-config-idiomatic-order/releases) nor on [npm](https://www.npmjs.com/package/stylelint-config-idiomatic-order):

![image](https://github.com/ream88/stylelint-config-idiomatic-order/assets/14821482/b0fc5392-1239-4749-acbe-113471968806)

Thanks !

**Comment by mrbinky3000** [comment]
I have a dependency error that is fixed in your code, but you forgot to publish your changes to npm.  Can you update?

**Comment by ream88** [comment]
Done

**Comment by julienw** [comment]
Thanks!
Would it be possible to push the tag to the repository as well?
